### ISSUE TITLE
Testing ASP 6.5.0-Kilo

### ISSUE THREAD

**Issue by mertyusaatag** [mertyusaatag/UA-Nodeset#1]
## Scope 

- [ ] All existing scripts 
- [ ] Report any warnings

**Comment by mpostol** [comment]
@mertyusaatag - I hope all models recovered using `ASP 6.5.0-Kilo` are generated and are in the repository?

Creation of the warning report we shall postpone up to the next version - hopefully, it will be fixed.

**Comment by mertyusaatag** [comment]
its duplicated with #11
