### ISSUE TITLE
Check if all models are uptodate

### ISSUE THREAD

**Issue by mpostol** [mertyusaatag/UA-Nodeset#11]
## Describe the problem

Not sure if all models have been generated using ASP 6.5.0-Kilo.

## Describe the solution you'd like

- The log file shall contain a message that it was generated using `ASP 6.5.0-Kilo`
- The log file should be generated together with the ModelDesign file
- It is a blocker for #1. After finishing close also the #1.

## List of models that the task is to be applied to

- [x] ADI
- [x] AML
- [x] AnsiC
- [x] AutoID
- [x] CAS
- [x] CNC
- [x] CommercialKitchenEquipment
- [x] CSPPlusForMachine
- [x] DEXPI
- [x] DI
- [x] DotNet
- [x] FDI
- [x] FDT
- [x] GDS
- [x] I4AAS
- [x] IA
- [x] IEC61850
- [x] IJT
- [x] IOLink
- [x] ISA-95
- [x] ISA95-JOBCONTROL
- [x] Machinery
- [x] MachineTool
- [x] MachineVision
- [x] MDIS
- [x] MTConnect
- [x] OpenSCS
- [x] PackML
- [x] PADIM
- [x] PlasticsRubber
- [x] PLCopen
- [x] PNEM
- [x] POWERLINK
- [x] PROFINET
- [x] Pumps
- [x] Robotics
- [x] Safety
- [x] Scales
- [x] Sercos
- [x] TMC
- [x] Weihenstephan

**Comment by mertyusaatag** [comment]
all files are executed with asp 6.5

**Comment by mpostol** [comment]
IEC61850 is missing. Reopen it and check again the rest.

**Comment by mpostol** [comment]
PlasticsRubber is also missing -  there is an open issue mpostol/UA-Nodeset#92 that is a blocker for this issue.

**Comment by eoursel** [comment]
Hi @mertyusaatag @mpostol I briefly tried this morning on 61850-7-3 and 61850-7-4 namespaces. 
Note that 61850-7-4 is dependent on 61850-7-3.  

The ModelDesign XML  file is generated without any error detected for 61850-7-3 and 61850-7-4. For 61850-7-4 i must include the 61850-7-3 to avoid any error messages . Not tested the ModelCompiler yet with these outputs;  

```
PS Z:\dev\code\OPCFoundation\UA-Nodeset\IEC61850> Z:\dev\Programs\mpostol\asp.exe --export .\Opc.Ua.IEC61850-7-4.ModelDesign.xml --namespace http://opcfoundation.org/UA/IEC61850-7-4  .\Opc.Ua.IEC61850-7-3.NodeSet2.xml .\Opc.Ua.IEC61850-7-4.NodeSet2.xml
Address Space Prototyping (asp.exe) Version 6.5.0.40483
Copyright(c) 2022 Mariusz Postol

\
Execution time = 253s
```

**Comment by mpostol** [comment]
@eoursel  I have checked the script recovering the model and everything looks OK. The model you may check out from `IEC61850\ModelDesign` folder. It seems that all dependencies are added to the script responsible to recover all models in concern. The script and all log files are also in the same folder. Let me know how it works for you.
