### ISSUE TITLE
Add `aml` documentation to generate wep help

### ISSUE THREAD

**Issue by mpostol** [mertyusaatag/UA-Nodeset#22]
## Describe the problem

- create *.aml files for each model - try to use the naming pattern as usual. For existing files 
  - rename the file according to the convention, 
  - commit to the repository
  - override the existing file with a new one
- copy *.aml files to the docs  folder for each model

it contributes to mpostol/UA-Nodeset#81

## List of models that the task is to be applied to

- [x] ADI
- [x] AML
- [x] AnsiC
- [x] AutoID
- [x] CAS
- [x] CNC
- [x] CommercialKitchenEquipment
- [x] CSPPlusForMachine
- [x] DEXPI
- [x] DI
- [x] DotNet
- [x] FDI
- [x] FDT
- [x] GDS
- [x] I4AAS
- [x] IA
- [ ] IEC61850
- [x] IJT
- [ ] IOLink
- [x] ISA-95
- [x] ISA95-JOBCONTROL
- [x] Machinery
- [x] MachineTool
- [x] MachineVision
- [x] MDIS
- [x] MTConnect
- [x] OpenSCS
- [x] PackML
- [x] PADIM
- [ ] PlasticsRubber
- [x] PLCopen
- [x] PNEM
- [x] POWERLINK
- [x] PROFINET
- [x] Pumps
- [x] Robotics
- [x] Safety
- [x] Scales
- [x] Sercos
- [x] TMC
- [x] Weihenstephan

**Comment by mertyusaatag** [comment]
@mpostol, As you know, solution cannot be created for IOLINK. also for plasticrubber should I do it for each file? Finally, we do not have a solution for the IEC6590 file.I created and committed the rest.
